
services:
  frontend:
    container_name: order-settlement-frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: order-settlement-frontend:latest
    ports:
      - '7103:3000'
    volumes:
      - ./:/app
    command: sh -c "if [ ! -f /app/node_modules ]; then npm install; fi && npm run dev"
